import type { CSSProperties } from "react";

export const pageStyles: Record<string, CSSProperties> = {
  page: {
    minHeight: "100vh",
    background: "#f4f9fb",
    padding: "28px",
    fontFamily: "Inter, ui-sans-serif, system-ui, sans-serif",
  },
  header: {
    maxWidth: "1200px",
    margin: "0 auto 24px auto",
    padding: "24px",
    border: "1px solid #d9e8ee",
    borderRadius: "12px",
    background: "#ffffff",
    boxShadow: "0 10px 28px rgba(18, 50, 63, 0.07)",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  compactHeader: {
    maxWidth: "1100px",
  },
  title: {
    margin: 0,
    color: "#12323f",
    fontSize: "32px",
    letterSpacing: "0",
  },
  subtitle: {
    margin: "6px 0 0 0",
    color: "#5f7680",
  },
  backButton: {
    padding: "12px 18px",
    border: "none",
    borderRadius: "8px",
    background: "#1f5d73",
    color: "#ffffff",
    fontWeight: "bold",
    cursor: "pointer",
  },
  card: {
    maxWidth: "1200px",
    margin: "0 auto 24px auto",
    padding: "24px",
    border: "1px solid #d9e8ee",
    borderRadius: "12px",
    background: "#ffffff",
    boxShadow: "0 10px 28px rgba(18, 50, 63, 0.06)",
    overflowX: "auto",
  },
  compactCard: {
    maxWidth: "1100px",
  },
  sectionTitle: {
    marginTop: 0,
    color: "#12323f",
    letterSpacing: "0",
  },
  subTitle: {
    margin: 0,
    color: "#12323f",
  },
  label: {
    display: "grid",
    gap: "8px",
    color: "#284653",
    fontSize: "14px",
    fontWeight: "bold",
  },
  input: {
    width: "100%",
    padding: "12px",
    border: "1px solid #c9dce3",
    borderRadius: "8px",
    fontSize: "15px",
    background: "white",
    color: "#12323f",
  },
  textarea: {
    minHeight: "110px",
    padding: "12px",
    border: "1px solid #c9dce3",
    borderRadius: "8px",
    fontSize: "15px",
    background: "white",
    color: "#12323f",
    resize: "vertical",
  },
  saveButton: {
    padding: "13px 18px",
    border: "none",
    borderRadius: "8px",
    background: "#0e9384",
    color: "white",
    fontWeight: "bold",
    cursor: "pointer",
  },
  cancelButton: {
    padding: "13px 18px",
    border: "none",
    borderRadius: "8px",
    background: "#61757d",
    color: "white",
    fontWeight: "bold",
    cursor: "pointer",
  },
  addButton: {
    padding: "10px 14px",
    border: "none",
    borderRadius: "8px",
    background: "#1f5d73",
    color: "white",
    fontWeight: "bold",
    cursor: "pointer",
  },
  editButton: {
    padding: "8px 12px",
    border: "none",
    borderRadius: "8px",
    background: "#1f5d73",
    color: "white",
    fontWeight: "bold",
    cursor: "pointer",
  },
  deleteButton: {
    padding: "8px 12px",
    border: "none",
    borderRadius: "8px",
    background: "#c2413b",
    color: "white",
    fontWeight: "bold",
    cursor: "pointer",
  },
  message: {
    marginTop: "16px",
    color: "#0e9384",
    fontWeight: "bold",
    textAlign: "center",
  },
  searchInput: {
    width: "100%",
    boxSizing: "border-box",
    padding: "12px",
    marginBottom: "18px",
    border: "1px solid #c9dce3",
    borderRadius: "8px",
    fontSize: "15px",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    border: "1px solid #d9e8ee",
    borderRadius: "10px",
    overflow: "hidden",
  },
  th: {
    textAlign: "left",
    padding: "14px",
    borderBottom: "1px solid #d9e8ee",
    color: "#284653",
    background: "#f4f9fb",
  },
  td: {
    padding: "14px",
    borderBottom: "1px solid #edf4f6",
    color: "#12323f",
    verticalAlign: "top",
  },
  actions: {
    display: "flex",
    gap: "8px",
    flexWrap: "wrap",
  },
  rowActions: {
    display: "flex",
    gap: "8px",
    flexWrap: "wrap",
  },
  detailsHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "12px",
  },
  smallText: {
    color: "#5f7680",
    fontSize: "12px",
  },
  totalBox: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "16px",
    borderRadius: "10px",
    background: "#e7f7f4",
    color: "#0b635d",
    fontSize: "18px",
  },
  lineTotalBox: {
    display: "grid",
    gap: "6px",
    padding: "10px 12px",
    borderRadius: "8px",
    background: "#f4f9fb",
    color: "#12323f",
  },
};
